### ISSUE TITLE
Long polling

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/web_hooks#32]
@DeepDiver1975 

How difficult would it be to support long polling?

I am thinking about a ```poll.php``` which the user (or better the client) opens (via GET) but which does not close its connection. ```publisher.php``` would then have to inform ```poll.php``` about changes so that ```poll.php```can print a new line to its out stream:

    {"action":"changed","path":"\/dir\/file.tex","user":"user","fileId":2517,"mimeType":"application\/x-tex"}

I image that those scripts are running in different contexts. Is inter php communication (maybe via shared memory) still possible?

If this would work clients no longer have to pull every x seconds for changes __without any network configuration__!

**Comment by LukeOwncloud** [comment]
<?php
    out("Long polling sleep demo...");
    $slept = 0;
    for($i=1;$i<99999;$i+=$i)
    {
      sleep($i);
      $slept += $i;
      out("Slept for ".($i)." seconds. Total sleep time: ".$slept." seconds.");
    }
    function out($s) {
      echo($s . "<br>");
      ob_flush();
      flush();
    }
    ?>

**Comment by DeepDiver1975** [comment]
We have been thinking about long polling in various areas of owncloud in the past.
The main issue is that a php process will continue to live over time - one process for each request.

In bigger installations this will be far too resource intensive.

Furthermore - php processes will be killed by the web server after a configurable time.

**Comment by LukeOwncloud** [comment]
Yes, scalability is an issue. However, this is an issue for every kind of instantaneous notification mechanism. One needs a permanent connection between server and each client. For small installation it is not be a problem though. And after all, this is an option can _can_ be enabled. Why not provide it for those who have capable hardware?

About killing the php process: I have a standard Ubuntu system with an Apache server and all default settings. Php processes live at least for 8000 seconds on my machine. Of course this is just an example...

Nonetheless, if the process lived only 60 seconds, the client would have to re-connected every minute. That is still better than polling every 30 seconds. Don't you think?

But my actual question was about inter php communication between ````publisher.php``` and ```poll.php```. Is it possible? 

PS: This ```poll.php``` could be disabled via an app/plugin setting.

**Comment by LukeOwncloud** [comment]
> poll.php has to query the database for any updates

That indeed seems difficult.

> But nobody is polling every 30 seconds - web_hooks implement pub-sub and the server is sending out notifications to the registered client.

Yes, web_hooks isn't polling. But the Desktop owncloud client is. Every 30 seconds by default.

**Comment by LukeOwncloud** [comment]
> unrelated to this repo

So this repo is not meant to be used by the client? It would be a very nice enhancement. The only thing that is missing is poll.php ...

**Comment by DeepDiver1975** [comment]
This repo is only for topics related to web_hooks and pub/sub.

Any kind of polling (which I doubt can be implemented with our current architecture) is not topic of this repo.

**Comment by LukeOwncloud** [comment]
Okay. Then I just close this ticket. Maybe you can add a note to the README.md what web_hooks actually means and what it is good for...

**Comment by DeepDiver1975** [comment]
> Maybe you can add a note to the README.md what web_hooks actually means and what it is good for...

Done - by reffing some article on wikipedia - THX

https://github.com/owncloud/web_hooks/commit/54354265fc210f94f95d624e7e5b01993a27202a#diff-04c6e90faac2675aa89e2176d2eec7d8R6

**Comment by LukeOwncloud** [comment]
@DeepDiver1975 

Thanks for your answers! Just one more:

I figure out how long polling can be provided. For testing I extended web_hooks: It is just one additional route in ```routes.php```, 5 lines in addNotifications() in ```publisher.php```, and a new ```pollcontroller.php``` class. The rest is the same. To avoid duplicated code adding it to web_hooks would make sense. To have clearly separated apps, a new app would seem better. What do you think? In case of a new app: Can you create a new repository for this "long polling" app?

**Comment by DeepDiver1975** [comment]
Because polling has really nothing to do with pubsub I defiantly don't want this in here. A new app might make sense - but I'm still questioning the validity of this approach.

Furthermore we already use event source in some selected areas to get a similar behavior.
But still this solution does not scale and is kind of useless for e.g. client sync.

**Comment by LukeOwncloud** [comment]
Just wanted to share that I created a dedicated app for long-polling -> https://github.com/LukeOwncloud/long-polling-for-owncloud
